require 'resque/plugins/heroku_scaler/version'
require 'resque/plugins/heroku_scaler/config'
require 'resque/plugins/heroku_scaler/manager'
require 'resque/plugins/heroku_scaler/worker'
require 'resque/plugins/heroku_scaler/resque'
require 'resque/plugins/heroku_scaler'
