require 'resque/plugins/resque_heroku_scaler/version'
require 'resque/plugins/resque_heroku_scaler/config'
require 'resque/plugins/resque_heroku_scaler/manager'
require 'resque/plugins/resque_heroku_scaler/worker'
require 'resque/plugins/resque_heroku_scaler/resque'
require 'resque/plugins/resque_heroku_scaler'
